import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// import Footer from "./components/Footer";
import type { Viewport } from "next";


// example fonts - need to implement during front-end sprint
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// change metadata
export const metadata: Metadata = {
  title: "Progresywna aplikacja webowa - trening oraz dieta",
  description: "Generated by create next app",
  generator: "Next.js",
  manifest: "/manifest.json",
  keywords: ["nextjs, next14", "pwa", "next-pwa"],
  icons: [
    { rel: "apple-touch-icon", url: "icons/icon-128x128.png" },
    { rel: "icon", url: "icons/icon-128x128.png" },
  ],
};

// Define your viewport settings
export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false, // Ensures users can't zoom
  viewportFit: 'cover', // Ensures the viewport fits edge-to-edge (on iOS devices)
  colorScheme: 'light dark', // Supports both light and dark themes
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
